# Generated by Django 3.0.7 on 2020-09-18 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
